name: Some kind of one-off build

# really should be on a cron, here it's just push to let me test in a branch
# if it was in main, I could use workflow_dispatch
on: [ push ]

jobs:
  daily-compiler:
    name: Build daily compilers
    runs-on: [ 'ce','ubuntu' ]
    strategy:
      matrix:
        include:
          - { image: clang, build_name: llvm, command: build.sh, build: llvm-trunk }
          - { image: clang, build_name: clang, command: build.sh, build: trunk }
          - { image: gcc, build_name: gcc, command: build.sh, build: trunk }

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Daily build of ${{ matrix.build_name }}
        id: build
        run: |
          REVISION_FILENAME=/opt/.buildrevs/${{ matrix.build_name }}
          REVISION=""
          if [[ -f "${REVISION_FILENAME}" ]]; then
              REVISION=$(cat "${REVISION_FILENAME}")
          fi
          mkdir dist
          echo ::group::Docker build
          docker run -v$(pwd)/dist:/dist --rm compilerexplorer/${{ matrix.image }}-builder \
            bash ${{ matrix.command }} ${{ matrix.build }} \
            /dist "${REVISION}" | tee output.log
          echo ::endgroup::
          gawk -e 'match($0, /^ce-build-(\w+):(.*)/, m) { print "::set-output name=" m[1] "::" m[2]; }' output.log
      - name: Print outputs from previous
        run: |
          echo STATUS ${{ steps.build.outputs.status }}
          echo REVISION ${{ steps.build.outputs.revision }}
          echo OUTPUT ${{ steps.build.outputs.output }}
